# Generated by Django 2.2.2 on 2019-07-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplanner', '0002_auto_20190701_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='b_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='b_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
