# Generated by Django 2.2.2 on 2019-07-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplanner', '0003_auto_20190701_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='has_ingredients',
            field=models.BooleanField(default=False),
        ),
    ]
