# Generated by Django 2.2.2 on 2019-07-18 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mealplanner', '0004_fooditem_has_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_ingredient', to='mealplanner.FoodItem')),
                ('recepie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_recipe', to='mealplanner.FoodItem')),
            ],
        ),
        migrations.DeleteModel(
            name='RecepieIngredient',
        ),
    ]
